# Basic Information 
title: Guilherme Espindola-Winck  
position: Associate Professor
affiliation: Centrale Lille Institute
affiliation_link: https://centralelille.fr
affiliation_logo: ./assets/img/c_centralelille_rvb_300sm.png
email: guilherme.espindola (at) centralelille.fr
email2: guilherme.espindola-winck (at) univ-lille.fr

# Search Engine Optimization (SEO)
keywords: G. E. Winck, G. Espindola-Winck
canonical: https://gespindola-winck.com
description: Guilherme Espindola-Winck is an Associate Professor in Automatic Control.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=ZFS5jYQAAAAJ&hl=fr&oi=ao=fr&oi=ao
#github_link: https://github.com/yaoyao-liu/
linkedin: https://fr.linkedin.com/in/guilherme-espindola-winck-952956b0
#twitter: https://twitter.com/YaoyaoLiu1/

# Images 
avatar: ./assets/img/guilherme-espindolawinck.jpeg
#favicon: ./assets/img/favicon.png
#favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
#footnote: Feel free to use my website's source code.
#footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
#clustrmaps_id: CJD8XwsJhSyQ6sbsU-Gw0cNcUlbah7KW3xvHN2QlwW0

# The following files will be removed from the generated website.

